name: ginkgo-test
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  ginkgo:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: run ginkgo
        run: go run github.com/onsi/ginkgo/v2/ginkgo -r -v
